version: "3"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE  # optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=raspberrypi.local
      - SERVERPORT=51820  # optional
      - PEERS=2  # optional
      - PEERDNS=auto  # optional
      - INTERNAL_SUBNET=10.13.13.0  # optional
      - ALLOWEDIPS=0.0.0.0/0  # optional
      - LOG_CONFS=true  # optional
    ports:
      - "51820:51820/udp"
    volumes:
      - ./config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
