version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rushi12345
      MYSQL_DATABASE: user_service
      MYSQL_USER: root
      MYSQL_PASSWORD: rushi12345
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data: